[package]
name = "cw-sauron"
version = "1.0.0"
edition = "2021"
description = "Cloudwatch CLI Tool"
license = "MIT"
repository = "https://github.com/dawsonfi/sauron"

[dependencies]
aws-config = "0.9.0"
aws-sdk-sfn = "0.9.0"
aws-smithy-types = "0.39.0"
aws-smithy-http = "0.39.0"
tokio = { version = "1", features = ["full"] }
chrono = "0.4.19"
mockall_double = "0.2.1"
mockall = "0.11.0"
async-trait = "0.1.53"