name: Release Pipeline

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cdk:
    environment: aws
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1    
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - name: Deploy stack
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  build:
    needs: cdk
    environment: aws
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
  release:
    if: contains(github.event.head_commit.message, 'release')
    needs: build
    environment: crates
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      run: cargo build --release
    - name: Login
      run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
    - name: publish
      run: cargo publish


